### ISSUE TITLE
INTERNAL ASSERT FAILED. Pytorch versions?

### ISSUE THREAD

**Issue by segermans** [DeepSceneSeg/EfficientPS#15]
Dear authors,

Thanks again for your great contribution. I want to use the output of EfficientPS for further processing in my own research. Therefore, my main interest is running inference using your pretrained mapillary vista's (or temporarily Cityscapes) model. However, I get an error when running the test-file with multiple GPU's with nGPUs set to 1. A transcript of the record is provided at the bottom. I tried updating PyTorch to 1.6, but no luck either. Do you have a clue what it could be?
I recon it could have to do something with the provided pre-trained model, as training does seem to work..

Additional information:
- I set up the environment exactly as recommended, using the `environment.yml` and `requirements.txt` files. 
- When installing efficientPS implementation, I also get a lot of depracated warnings. However, it does finalize the installation.
- Training does seem to work as it should

My settings:
- CUDA 10.2.89
- GCC 8.4.0
- Python 3.7

Running `python -c 'from torch.utils.collect_env import main; main()` gives the following:
```
(efficientPS_env) segetak@cmtcde5u157:~/thesis/EfficientPS$ python -c 'from torch.utils.collect_env import main; main()'
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.5 LTS
GCC version: (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 980
Nvidia driver version: 460.32.03
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] torch                     1.4.0                    pypi_0    pypi
[conda] torchvision               0.5.0                    pypi_0    pypi
```
And finally, the error itself:
```
(efficientPS_env) segetak@cmtcde5u157:~/thesis/EfficientPS$ ./tools/dist_test.sh pre_trained_models/efficientPS_cityscapes/config/efficientPS_multigpu_sample.py pre_trained_models/efficientPS_cityscapes/model/model.pth 1 --eval panoptic
loading annotations into memory...
Done (t=0.17s)
creating index...
index created!
Traceback (most recent call last):
  File "./tools/test.py", line 169, in <module>
    main()
  File "./tools/test.py", line 135, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location='cpu')
  File "/lhome/segetak/anaconda3/envs/efficientPS_env/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 218, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/lhome/segetak/anaconda3/envs/efficientPS_env/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 194, in _load_checkpoint
    checkpoint = torch.load(filename, map_location=map_location)
  File "/lhome/segetak/anaconda3/envs/efficientPS_env/lib/python3.7/site-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/lhome/segetak/anaconda3/envs/efficientPS_env/lib/python3.7/site-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f4277e73193 in /lhome/segetak/anaconda3/envs/efficientPS_env/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7f4217fd79eb in /lhome/segetak/anaconda3/envs/efficientPS_env/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7f4217fd8c04 in /lhome/segetak/anaconda3/envs/efficientPS_env/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x6c6536 (0x7f427ce5c536 in /lhome/segetak/anaconda3/envs/efficientPS_env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x295a74 (0x7f427ca2ba74 in /lhome/segetak/anaconda3/envs/efficientPS_env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: _PyMethodDef_RawFastCallDict + 0x24d (0x55e2e15d044d in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #6: _PyCFunction_FastCallDict + 0x21 (0x55e2e15d05d1 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #7: _PyObject_Call_Prepend + 0x63 (0x55e2e15ce4d3 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #8: PyObject_Call + 0x6e (0x55e2e15c0ffe in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #9: <unknown function> + 0x9e62d (0x55e2e153862d in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #10: _PyObject_FastCallKeywords + 0x128 (0x55e2e1606968 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #11: _PyEval_EvalFrameDefault + 0x52fe (0x55e2e166c39e in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #12: _PyEval_EvalCodeWithName + 0x5da (0x55e2e15aeb0a in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #13: _PyFunction_FastCallDict + 0x1d5 (0x55e2e15af925 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #14: _PyObject_Call_Prepend + 0x63 (0x55e2e15ce4d3 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #15: <unknown function> + 0x16bd5a (0x55e2e1605d5a in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #16: _PyObject_FastCallKeywords + 0x128 (0x55e2e1606968 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #17: _PyEval_EvalFrameDefault + 0x49e6 (0x55e2e166ba86 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #18: _PyEval_EvalCodeWithName + 0x2f9 (0x55e2e15ae829 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #19: _PyFunction_FastCallKeywords + 0x387 (0x55e2e15ff107 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #20: _PyEval_EvalFrameDefault + 0x14e5 (0x55e2e1668585 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #21: _PyEval_EvalCodeWithName + 0x2f9 (0x55e2e15ae829 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #22: _PyFunction_FastCallKeywords + 0x325 (0x55e2e15ff0a5 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #23: _PyEval_EvalFrameDefault + 0x416 (0x55e2e16674b6 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #24: _PyEval_EvalCodeWithName + 0x2f9 (0x55e2e15ae829 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #25: _PyFunction_FastCallKeywords + 0x387 (0x55e2e15ff107 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #26: _PyEval_EvalFrameDefault + 0x14e5 (0x55e2e1668585 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #27: _PyFunction_FastCallKeywords + 0xfb (0x55e2e15fee7b in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #28: _PyEval_EvalFrameDefault + 0x416 (0x55e2e16674b6 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #29: _PyEval_EvalCodeWithName + 0x2f9 (0x55e2e15ae829 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #30: PyEval_EvalCodeEx + 0x44 (0x55e2e15af714 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #31: PyEval_EvalCode + 0x1c (0x55e2e15af73c in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #32: <unknown function> + 0x22cf14 (0x55e2e16c6f14 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #33: PyRun_FileExFlags + 0xa1 (0x55e2e16d1331 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #34: PyRun_SimpleFileExFlags + 0x1c3 (0x55e2e16d1523 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #35: <unknown function> + 0x238655 (0x55e2e16d2655 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #36: _Py_UnixMain + 0x3c (0x55e2e16d277c in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)
frame #37: __libc_start_main + 0xe7 (0x7f4281a36bf7 in /lib/x86_64-linux-gnu/libc.so.6)
frame #38: <unknown function> + 0x1dcff0 (0x55e2e1676ff0 in /lhome/segetak/anaconda3/envs/efficientPS_env/bin/python)

Traceback (most recent call last):
  File "/lhome/segetak/anaconda3/envs/efficientPS_env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/lhome/segetak/anaconda3/envs/efficientPS_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/lhome/segetak/anaconda3/envs/efficientPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/lhome/segetak/anaconda3/envs/efficientPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/lhome/segetak/anaconda3/envs/efficientPS_env/bin/python', '-u', './tools/test.py', '--local_rank=0', 'pre_trained_models/efficientPS_cityscapes/config/efficientPS_multigpu_sample.py', 'pre_trained_models/efficientPS_cityscapes/model/model.pth', '--launcher', 'pytorch', '--eval', 'panoptic']' returned non-zero exit status 1.
```

**Comment by 95maddycode** [comment]
I got the same error. Did you already solve it?

**Comment by segermans** [comment]
Nope. Have not worked on it either, but will continue with it this week. Let me know if you found a solution (or preferably, the authors :) ).

Cheers.

**Comment by mohan1914** [comment]
The model was trained with torch 1.7.1. I have updated the repo to support 1.7.1
Please reinstall. Hopefully, there shouldn't be any problem running the model then.

**Comment by 95maddycode** [comment]
It works perfectly after updating to 1.7.1

**Comment by segermans** [comment]
Mine also works! Thanks.
