### ISSUE TITLE
Fail to open efficientPS_cityscapes.zip

### ISSUE THREAD

**Issue by felipecadar** [DeepSceneSeg/EfficientPS#35]
I flowed the instructions to create a conda environment. When i tried the test script i got the error:
```
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

But could solve it updating the mmcv from 0.5.9 to 0.6.0 .

Then, when i ran the script i got this error:

```
Traceback (most recent call last):
  File "tools/test.py", line 169, in <module>
    main()
  File "tools/test.py", line 135, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location='cpu')
  File "/opt/miniconda3/envs/env/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 224, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/opt/miniconda3/envs/env/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 200, in _load_checkpoint
    checkpoint = torch.load(filename, map_location=map_location)
  File "/opt/miniconda3/envs/env/lib/python3.7/site-packages/torch/serialization.py", line 587, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/opt/miniconda3/envs/env/lib/python3.7/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:222] . file not found: efficientPS_cityscapes/version
```
Seems like i'm missing something in the weights zip file :/ 

The command i used: 
```
(env) Singularity> python tools/test.py configs/efficientPS_singlegpu_sample.py models/efficientPS_cityscapes.zip --eval panoptic
```

**Comment by gayathri1818** [comment]
From where did you download the config and the model file?

**Comment by felipecadar** [comment]
I used the link on the readme to download the model file for cityscapes and the config file available on this repo.

**Comment by mohan1914** [comment]
The link for the downloads works fine. Maybe you can try again once more.
