### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### ISSUE THREAD

**Issue by cskate1997** [DeepSceneSeg/EfficientPS#51]
(venv) root@cc3180440f4b:/opendr/src/opendr/perception/panoptic_segmentation/efficient_ps/algorithm/EfficientPS# python tools/convert_cityscapes.py ./data_2/ ./data/cityscapes/
Loading Cityscapes from ./data_2/
Converting train ...
  0%|                                                                                                                    | 0/2974 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "tools/convert_cityscapes.py", line 163, in __call__
    coco_ann_i = pct.create_annotation_info(
  File "/opendr/venv/lib/python3.8/site-packages/pycococreatortools/pycococreatortools.py", line 99, in create_annotation_info
    segmentation = binary_mask_to_polygon(binary_mask, tolerance)
  File "/opendr/venv/lib/python3.8/site-packages/pycococreatortools/pycococreatortools.py", line 48, in binary_mask_to_polygon
    contours = np.subtract(contours, 1)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tools/convert_cityscapes.py", line 198, in <module>
    main(parser.parse_args())
  File "tools/convert_cityscapes.py", line 76, in main
    for coco_img, coco_ann in tqdm.tqdm(pool.imap(worker, img_list, 8), total=total):
  File "/opendr/venv/lib/python3.8/site-packages/tqdm/std.py", line 1166, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 420, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
(venv) root@cc3180440f4b:/opendr/src/opendr/perception/panoptic_segmentation/efficient_ps/algorithm/EfficientPS# 

How can I solve the above error

I have installed pycococreator and pycocotools from https://github.com/waspinator/pycococreator

**Comment by KJYoung** [comment]
I don't know whether this is the valid solution, at least it worked.

CHANGE(pycococreatortools library's pycococreatortools.py binary_mask_to_polygon function(the error point):
`contours = np.subtract(contours, 1)`
to
`contours = [ np.subtract(contour, 1) for contour in contours ]`
